### ISSUE TITLE
Option to "eject" out of electrode ?

### ISSUE THREAD

**Issue by donszek** [electrode-io/electrode#101]
Hi, is it possible (or future plan) to allow users to eject their app out of electrode with all the dependencies inserted into package.json and necessary scripts?

**Comment by citelao** [comment]
It's not possible currently, and from what I gather it's not intended to be.

**Comment by jchip** [comment]
theoretically it should be straightforward to copy the archetype config and scripts into a directory under your app and move the dependencies into your package.json.  The archetype code doesn't hardcode where its location is but since there is two parts (the main archetype and the dev part)  some config scripts does require the other by name so that needs some updates.  This use is really not the intend of the archetype but the option is open.

**Comment by jchip** [comment]
I consider eject like a 100% configurable option and it's not aligned with the design goal of archetype types.  we are very resource constraint so close this for now.
