### ISSUE TITLE
Css source maps is not working properly. Is it possible to have class names instead of hashed names?

### ISSUE THREAD

**Issue by lnaia** [electrode-io/electrode#113]
During development (dev/hot tasks), I want to see the css class names in a not so hashed fashion.
This is what currently shows: _3kRNMU8RHfZdxA8s_LtRgF _29bopz2RZr8eY8DaYnclXP
Something along the lines of: [name]__[local]___[hash:base64:5] would be perfect. 

Question is, how to enable this behaviour? 
ps: I'm running the project on express, if it helps. 

I've been looking at past issues as well, and tried and empty call to cssModuleHook(), and even made it so, that the generateScopedName returned only the name, both to no success.

**Comment by LeeFrancis** [comment]
This is related to [this question](https://github.com/electrode-io/electrode/issues/105), but I havent figured out how to change the compiled js, only the server side rendered markup.

**Comment by ananavati** [comment]
@darkbls 

by-default the `generatedScopeName` is `[hash:base64]`
```
options.generateScopedName = options.generateScopedName || "[hash:base64]";
```

LOC: https://github.com/electrode-io/electrode/blob/26be7d987662131c0d9489f0340c31401378181d/packages/electrode-archetype-react-app/supports.js#L8

> re: Something along the lines of: [name][local][hash:base64:5] would be perfect.

your custom-config option can be passed in your call to `supports.cssModuleHook()`

**Comment by darkbls** [comment]
I noticed it, but it does not work as expected.
I've changed the generateScopedName before, to other names or functions, but still the result is always the same.

The options I set, always reached the support.js correctly. Even if I change the original to:
```
    options.generateScopedName = "[name]"; // or
    options.generateScopedName = function (name, filepath, css) {
      return name;
    };
```

The function receives correct files, returns correct values. The end result is what does not change regardless of code.  Inspecting elements, on the DOM of any given browser, I can see only that the dom elements always have hashed class names, instead of say, any other of the options configured at the options.generateScopedName property.

**Comment by Patricknew** [comment]
@ananavati 
I'm still having the same problem, after adding in server "`supports.cssModuleHook({generateScopedName: "[local]"});`". 
It's not overriding the default `"[hash:base64]" ` from 'electrode-archetype-react-app'. Can you share more details please?

**Comment by Patricknew** [comment]
I also tried this:

`supports.load({
  cssModuleHook: {
    generateScopedName: '[local]',
  }
})
 .then(() => {
    const config = electrodeConfippet.config;
    SSRCaching.enableCaching();
    SSRCaching.setCachingConfig(cacheConfig);
    require("./express-server")(config); 
  });`

Still no luck. I'm new to electrode. Appreciate any help!
