### ISSUE TITLE
update node to >= 8 for electrode-archetype-react-app

### ISSUE THREAD

**Issue by kishorenekkalapudi** [electrode-io/electrode#1253]
@jchip 
filter-scan-dir require  node >= 8

https://github.com/jchip/filter-scan-dir/blob/master/package.json#L59

https://github.com/electrode-io/electrode/blob/v5.x.x/packages/electrode-archetype-react-app/package.json#L30

**Comment by jchip** [comment]
yes, since node 6 reached EOL we aren't really concerned with using features that's not compatible with it anymore.  If you must use node 6, you should ensure you have lockfile and not update your dependencies.

we could update the engine fields, but as far as I know, npm isn't enforcing that anyways.

**Comment by kishorenekkalapudi** [comment]
Thank you
