### ISSUE TITLE
Adding @xarc/opt-stylus does not add Stylus support.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [electrode-io/electrode#1764]
**Describe the bug**

Adding `@xarc/opt-stylus` as a dependency does not give stylus support to an Electrode X project.

**To Reproduce**

1. Init new repo with `@xarc/create-app`
1. Run `npm install`
1. Run dev, verify system works correctly.
1. Install package: `npm install --save @xarc/opt-stylus`, add a simple `.styl` file, and import it in a `.js` file
1. Run dev again
1. Get this error initially, after which the subapp just stops rendering entirely even after repeatedly restarting the dev server.

![image](https://user-images.githubusercontent.com/5187404/100973555-99608600-34ef-11eb-83d0-a9647591c8a2.png)

Subsequently, it just gives syntax errors showing up in DevTools:

![image](https://user-images.githubusercontent.com/5187404/100973596-b1d0a080-34ef-11eb-92b2-823fef63dfc1.png)

**Expected behavior**

The styl file is incorporated and there's no errors

**Screenshots**

**Desktop (please complete the following information):**

## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
 - Memory: 655.67 MB / 16.00 GB
 - Shell: 5.0.16 - /usr/local/bin/bash
## Binaries:
 - Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
 - Yarn: 1.22.0 - /usr/local/bin/yarn
 - npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## Browsers:
 - Chrome: 86.0.4240.198
 - Firefox: 83.0
 - Safari: 14.0

**Electrode Version**

Electrode X

**Additional information**

The absolutely most baffling part is that adding and then removing `@xarc/opt-postcss` as a dependency bizarrely fixes the problem:

```
$ npm i --save @xarc/opt-postcss
$ npm uninstall --save @xarc/opt-postcss
$ rm -rf node_modules
$ npm i
$ npm run dev # compiles fine
```

🤷‍♂️

**Comment by jchip** [comment]
yes, `@xarc/opt-postcss` is actually need for all styling support because any kind of CSS compiling depends on PostCSS.

the `sugarss` module not found error is webpack's style loader trying to compile stylus using sugarss syntax and can't find it.

what you did at with install/uninstall should not have work after you uninstall it, something with `npm uninstall` maybe, or webpack cache.

I think we can add a check to log warning if any styling option is enable w/o `@xarc/opt-postcss`
