### ISSUE TITLE
How might I use Electrode without Node.js?

### ISSUE THREAD

**Issue by ccorcos** [electrode-io/electrode#188]
At my company, we have an existing Python backend. So I'm curious how I could use some of these awesome tools for the frontend only.

**Comment by citelao** [comment]
The frontend is basically React + Redux + Webpack. You can integrate that into your existing process fairly easily if you use those tools individually.

The backend (server-side rendering and all that jazz) requires Node.JS to run, since it's running JS on the server. You'll need a way to run JS on the server if you want that too.

**Comment by ccorcos** [comment]
I'm just curious what the pattern is for building application with modular redux components using all the electrode build tools and scaffolding without all the Node.js stuff.

**Comment by citelao** [comment]
Electrode's build tools are just a specific configuration of Webpack. The meat of Electrode's code is a server plugin that can render client routes on the server.

**Comment by jchip** [comment]
a lot of electrode app archetype code for for build time compiling, processing, and bundling.  The task `gulp dev` also runs a Node server, which electrode also provide.  It's possible to use a different backend than Node for the server, but that workflow requires some fair amount of changes.
