### ISSUE TITLE
Forking archetypes

### ISSUE THREAD

**Issue by karlhorky** [electrode-io/electrode#254]
Hi there, first of all thanks for this awesome project! It enables so many powerful new technologies and makes them relatively easy to configure.

My question is whether there is any guidance on how to fork and modify the archetypes. We need specific things for our project that will not be contributable back to upstream.

Up until now we envisioned forking the repo, renaming the modules (using scoped npm packages) and then being able to keep up to date with pulling from upstream:

https://github.com/electrode-io/electrode/compare/master...kununu:dev?expand=1

Is there a better way of doing this? I tried searching through the docs and the issues but I didn't find anything.

cc @kaytcat @FreaKzero

**Comment by cross311** [comment]
@karlhorky My team has gone down the route of just creating NPM package wrappers for each of the configurations (eslint, babel, gulp).  We then use Jest for testing instead of karma.  My team has access to a private npm repository (we are also using learna for our packages) so it is easy for use to register our wrapper packages.  Our wrapper packages extend the electrode configurations where it makes sense and then add our own rules as overrides.  We actually use airbnb's eslint configuration as a base extension.

For webpack, electrode does a good job in the app repositories at auto extending the `webpack.config.js`, `webpack.config.dev.js`, and other environment ones that are in the root of the app repo.  So you can inject your own aliases and other things, but still getting electrode base webpack config (which has some really nice things).

In terms of generators, we have created our own because the generators at this point do not have a great place to hook in and extend. Also side note: Yoeman does not like scoped generator packages, so you can to create your own name that is not scoped.  We started with the generated code for first round then after finding what we were changing we then created our own generator.

 We are still working through some of the bits and pieces, but we are able to get 90%+ of electrodes magic and still give it our personal touch.

This is just what we have done, would love to hear if anyone else has come up with other ways?

**Comment by tbohlen** [comment]
As a follow on to your comment, @cross311 I would love to see more documentation in this repo about how to extend the gulp file. The examples in the archetype are nice, but I feel I'm faced with reading through a bunch of code to figure out how it all works! Are there any resources for learning this that you or others could point me towards?

**Comment by karlhorky** [comment]
@cross311 Cool, thanks for the extensive, thoughtful response!

So if I'm understanding correctly, you're doing things like this:

### ESLint configuration
- custom configuration in private module
- included in project in an `.eslintrc` file via [`checkCustom`](https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app/arch-gulpfile.js#L94-L100)

### Babel configuration
- custom configuration in private module
- included in project in a `.babelrc` file via [`extendBabelLoader`](https://github.com/electrode-io/electrode/pull/168)

### Gulp configuration
- custom configuration in private module
- included in the project via the `gulpfile.js` 

### webpack configuration
- custom configuration in project via `webpack.config.js` and `webpack.config.dev.js`

### Custom generator
- for changing the files and structure of scaffolding of new projects

Do you have public links for any of these? Would be awesome to see a gist or more fleshed-out example.

---

> and put in extend files in your component / app repositories

Hm, this makes me think that my assumptions about the configuration above may be incorrect... Or are the "extend files" the `.babelrc` and the `.eslintrc` files.

> We then use Jest for testing instead of karma.

Do you add these dependencies just via the app repository? I guess Karma is still installed in your app project as a dependency?

**Comment by karlhorky** [comment]
Our planned strategy consists of:

- forking
- pulling in updates from upstream via `backstroke` or similar

similar to what's outlined here: https://github.com/facebookincubator/create-react-app/issues/682

This has the following benefits:

- we still stay up to date with the upstream
- we have finer-grained control over what the archetypes provides us
  - we control which dependencies they have
  - we can change any behavior that is not already extensible

However, it doesn't come without downsides:

- effort of having to maintain and publish our own packages
- we need to resolve merge conflicts from upstream

**Comment by karlhorky** [comment]
Ok, I've got something working. It was a bit of work:

1. I scoped the package names that needed scoping and bumped the version numbers: https://github.com/kununu/electrode/pull/1/files

2. I tried to `npm install` in order to publish, but it didn't work because there is a circular dependency between `electrode-archetype-react-app-dev` and `electrode-webpack-reporter`.

3. I removed the dependency and tried to install again. This also didn't work because of some dependency issues which I didn't end up figuring out.

4. Instead, I reverted the changes from 1. and use fresh un-scoped packages to install.

5. I manually scoped all packages and references of every package  (also in their respective `node_modules`) until `npm publish` worked.

6. I changed my application code to point at these new scoped packages: https://work.karlhorky.com/electrode-scoped-archetypes-demo/update-dependencies/

This workflow could probably be improved if Electrode wants to support people forking their own archetypes.

**Comment by karlhorky** [comment]
Next up: setting up Backstroke.

**Comment by jchip** [comment]
Our original internal archetype modules are all scoped with `@walmart/` actually.  I didn't think forking could be so difficult, but I never tried it.  The circular dependencies are not a big issue.  webpack-reporter only depend on the archetype in dev mode for development.  The archetypes pull in a published version.

**Comment by jshado1** [comment]
@cross311 how did you handle using Jest instead of Electrode's built-in testing? I detest Karma and the Electrode test config is too rigid and hides too many config settings (like for Mocha), so we'd really like to switch.
