### ISSUE TITLE
Override a webpack.config partial without replacing it

### ISSUE THREAD

**Issue by eosmont** [electrode-io/electrode#337]
Hi

**tl:dr :** is it possible to override the configuration without the need of use the "replace" addOption ?

I want to override the "resolve" section of the webpack.config.js, with merging only (no replace in addOption). 

By observing webpack-config-composer's module code, I saw that the merging is done with the use of lodash's mergeWith. And it tries to merge an object (my config chunk), with a set of functions in the partials : 

My config : 
```
{ _resolve: { order: 9002, config: { resolve: [Object] } } }

```
Partials : 
```
{ 
	[...]
	_resolve: { config: [Function: config]},
	[...]
}
```

I wonder if lodash's mergeWith accepts the the merging of both function and object, but I think that is not the case.

**Comment by jchip** [comment]
You are looking at the internals of how the config composer holding these partials.

To merge your config, you just need to export an object from your custom `webpack.config.js` file:

```js

module.exports = {
  resolve: {
     ...
  }
};
```

The issue is the resolve section uses arrays, like this:

```js
{
   resolve: { 
      module: [ "/path1", "/path2" ],
      plugins: [ ... ]
   }
}
```

Merging would join those arrays together.  Overriding the resolve section is really not recommended because that's the trickiest part.
