### ISSUE TITLE
Query params info is missing in match.renderProps

### ISSUE THREAD

**Issue by adaniliuk** [electrode-io/electrode#485]
Hello, 

Could you please help to solve the issue with missing query info in location property passed to the components on the server side?

**Steps to reproduce:**
1. Try to open any server side rendered page with query string parameters in the url
2. Check location parameter

**Current behavior:**
`location.query` is empty object `{}`

**Expected behavior:**
`location.query` object contains parsed query parameters.

**Possible solution:**
Change the following line https://github.com/electrode-io/electrode/blob/762edbafdcd083dbdb0a7978682a08b85b8e8640/packages/electrode-redux-router-engine/lib/redux-router-engine.js#L34 to: 

```js
const location = req.url;
```

node version - 7.10.0
electrode-redux-router-engine version - 1.4.0

**Comment by jchip** [comment]
accessing the query info isomorphically is not exactly trivial.

- on the browser you can directly parse `window.location` within your component code
- but that doesn't work on the server because depending on the web framework (express, hapi, koa) the query params are available differently, plus you don't automatically have access to `request` in your UI code, and you don't want to explicitly ref `request` there anyways.

@dvonlehman has been working on some modules that makes things like config, request, and cookies access isomorphic transparently by using the react context API.  It's in beta internally at WML right now but he will be adding them to OSS soon.  I think making isomorphic query param access transparent is also a good feature to add so we will add it to the list.
