### ISSUE TITLE
Custom 404

### ISSUE THREAD

**Issue by codingcircus** [electrode-io/electrode#560]
Is it possible to send custom 404 pages with the Electrode Redux Router Engine, when some redux actions return an error?

Let's say for example I have an application, that serves books. When I navigate to a single book route (e.g. books/:name/) it would always return an https status of 200, even if the name doesn't exist. For SEO purposes it would be good, when when we could "hijack" the http status and still set it to 404.

**Comment by codingcircus** [comment]
I wrote a pull request for exactly this issue. https://github.com/electrode-io/electrode/pull/561

**Comment by jshado1** [comment]
I believe this is already possible by setting up middleware in `express-server.js` (which has access to the `response` object).

**Comment by seansean11eis** [comment]
@jshado1 after upgrading to `electrode-react-webapp`, it is possible to intercept the response object (since the `status/code` bugs were fixed), but this would require modifying the response after it was sent by `electrode-react-webapp`.

I think the `electrode-react-webapp` and `electrode-redux-router-engine` libraries might need to be modified to allow us to set up custom status handlers.

At the moment, the [`handleRoute` function](https://github.com/electrode-io/electrode/blob/master/packages/electrode-react-webapp/lib/express/index.js#L22) reverts to `response.status(status).send(data);` when a request receives a 404 status from the `electrode-redux-router-engine`.  This will always return a json object to the browser.  As far as I know, there is no way to respond with a 404 HTML page to the browser.  However, the walmart.com website seems to handle them correctly, which makes me wonder if they are using the same library.

The potential issue in the `electrode-redux-router-engine` library is that if you set up a catch-all (`*`) route for client-side 404's in your `routes.jsx` file, it will always return a 200 response code for all routes.  The library checks to see if the route that the user hit has a match in `routes.jsx` and since `*` catches any 404, you will always be returned a 200 status for the `electrode-redux-router-engine`.  This may need to be modified, unless there is some way around the problem on the client side.

I'd like to start working on a PR, but would also like to hear opinions/thoughts if you have any.

**Comment by codingcircus** [comment]
I already have an implementation for handling status codes in the express server in a forked version of version 2. So far I’d catch 404, 410 and 503 status code with custom html, as well as 301, 302, 307 and 308 with redirects. Do you think there is a need for other codes as well? 

Hopefully I can add it to Hapi and Koa as well in the next few days and open a new PR.

**Comment by seansean11** [comment]
@codingcircus sorry didn't realize you were working on this.  Interested in seeing your solution as well.

**Comment by devourment77** [comment]
Any update on custom 404s? 

I see two use cases:
- route not matched at all
- route + invalid param (EX: news/:id but do not know the id doesn't exist until checking the db).
