### ISSUE TITLE
Clap dev not working from Getting started if built with npm 5.4.2

### ISSUE THREAD

**Issue by LuckStock** [electrode-io/electrode#603]
Following new instructions from Get Started it fails with npm v5.4.2:
`ignite generate-app`

Installed with HapiJS and PWA.
If we remove node_modules and install with npm v5.3.0 everything works.

## Type of issue
Starting `clap dev` throws the error (shown below).

## My environment

* *OS version/details*: Windows 10, 64 bit
* *Node version:* v8.2.1
* *npm version:* v5.4.2
* *Version of yo :* 

## Current behavior:
 Execution Failed - Errors:
 1  shell cmd 'nodemon --delay 1 -C --ext js,jsx,json,yaml --watch .etmp\bundle.valid.log --watch src\server --watch config --exec babel-node src\server\index.js' exit code 1
    at error (D:\Projects\lab\ignite\node_modules\xsh\lib\exec.js:9:17)
    at shell.exec (D:\Projects\lab\ignite\node_modules\xsh\lib\exec.js:48:29)
    at D:\Projects\lab\ignite\node_modules\shcmd\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by sesteva** [comment]
+1

**Comment by qbitza** [comment]
See issue #583 It seems to be an issue with npm 5.3.0 and later, downgrade to npm 4.x until the issue has been resolved.

**Comment by didi0613** [comment]
@LuckStock @sesteva 
Thank you for reporting this.
After some investigation, the issue is to related to npm/lifecycle module, caused by: cannot read property 'pause' of undefined. References here: https://github.com/npm/npm/issues/18520

Solution:
Please downgrade your npm from 5.4.x into 5.3.x OR upgrade a more stable version 5.5.x.
Will add a proper message for usage of 5.4.x to ignite.
