### ISSUE TITLE
Question: Using entry.config

### ISSUE THREAD

**Issue by daxz1** [electrode-io/electrode#738]
Is there anymore information on how to setup/use entry.config.js? 
We have looked the doc which suggests creating a entry.config file but what do we do after that?

The script tags generated still point to main.bundle.js, however the entry points files are generated.

**Comment by jshado1** [comment]
To change the generated file names, set `entry` in your webpack config. See example at the top of #715 (or an updated example in [SO 48817853/758177](https://stackoverflow.com/a/48817853/758177)). In the provided examples, `main` → `app`. Note that it is not possible to change the other words in the filename because they're hard-coded into the script tag output string in Electrode's source code).

I'm not sure of the purpose of `entry.config.js`. The default built into Electrode seems to work regardless of what else is changed.

**Comment by daxz1** [comment]
Thanks for that.
