### ISSUE TITLE
Serving static files / robots.txt

### ISSUE THREAD

**Issue by brandonburkett** [electrode-io/electrode#780]
## Type of issue
Feature request/Question

What is the "electrode" way for serving static files.  EX: robots.txt or similar?  It looks like I can make a hapi plugin and define it in the default config (similar to pwa plugin), but was hoping there was a "electrodeStaticPaths" type functionality for this case.

Thanks!
Brandon

**Comment by jchip** [comment]
For our WalmartLabs use, static contents are usually served by CDN and edge servers.

For electrode, we don't really have an "electrode" way to serve static files.

It'd be the hapi/express/koa way depending on which of those framework you use, since electrode has samples on using all of them.

electrodeStaticPaths is just our Hapi plugin using hapi's inert, for a quick way to get our development flow to work.
