### ISSUE TITLE
Generator Electrode not starting electrify

### ISSUE THREAD

**Issue by suwigyarathore** [electrode-io/electrode#904]
Hi ,

I am reporting a bug regarding Generator Electrode

I was using generator electrode with yeoman installed it by below command

```npm install -g yo generator-electrode xclap-cli```

Then I generated project with below command

``` yo electrode```

After all installation I excecuted below command in generated project

```clap dev```

It does not start electrify server on http://locahost:2992/reporter to analyze bundle

**Comment by jchip** [comment]
Hi, we've been doing a lot of upgrades on webpack and react and electrify is outdated but we don't have resource to keep it up to date so it's been disabled.

Also, I recommend that you use electrode-ignite rather than the generator directly due to issues with settings etc that could make invoking the generator directly problematic.  electrode-ignite will also automatically check for updates.

see doc here https://docs.electrode.io/introduction/getting-started/start-with-ignite

Please ensure you do `npm uninstall -g yo generator-electrode` first if you do that.

**Comment by suwigyarathore** [comment]
Ahh thats a relief I was thinking what mistake I was doing. Is there is any way by which we can plug electrify with this newly created electrode app from ignite ?
