### ISSUE TITLE
proptypes should not be in production bundle

### ISSUE THREAD

**Issue by ajoshi0** [electrode-io/electrode#905]
## Type of issue
proptypes should not be in production bundle

Some how below code is not working as expected do we need to do something at pp level to enable it
https://github.com/electrode-io/electrode/blob/b72310851a17555663dbc245667ebd2e1686199f/packages/electrode-archetype-react-app-dev/package.json#L45

----

## My environment

* *OS version/details*: `OSX`
* *Node version:* `8.11.3`
* *npm version:* `5.10.0`

## Expected behavior
proptypes should not be in production js bundle

## Current behavior
proptypes are part of production js bundle

**Comment by ajoshi0** [comment]
@jchip @didi0613 any update on this its not working in apps at all

**Comment by jchip** [comment]
I verified that `propTypes` are removed from bundle in the sample app.

Note that `propTypes` from packages under `node_modules` don't get removed because published packages generally already transpiled their code with babel.

Currently we only babel files with `.jsx` extension to avoid transpiling all JS files in order to avoid slow build time.
